### ISSUE TITLE
undefined

### ISSUE THREAD

**Issue by pandaman0900** [wreed12345/GroupMe-Bots-With-Google-Apps-Script#8]
copy and paste bot id into the correct field, do not get a response from GroupMe text after uploading to server and changing bot URL. When try to run from google script, bot texts 'undefined'

any help appreciated

**Comment by wreed12345** [comment]
Did you follow the tutorial fully on the wiki?

**Comment by pandaman0900** [comment]
yes, tutorial was fully followed. texting "!hi" yields nothing as well

**Comment by wreed12345** [comment]
Hmm did you publish your most recent code ( in a new version), authorize
the app for public use ( no sign in required) and update the not to point
to the web app URL?

**Comment by pandaman0900** [comment]
figured out issue, thanks for the help!

**Comment by nlahn7** [comment]
@pandaman0900 do you know what the issue was and how you fixed it? I am having a similar problem
